### PR TITLE
Fix KeyboardEvent#key and allow `triggerKeyEvent` to receive keys instead of keycodes

### LINKED ISSUE #265: Update `triggerKeyEvent` to handle `code` and `key`.
From https://github.com/emberjs/ember-test-helpers/pull/258#discussion_r155963086:

> When I initially copied `keyEvent`, I continued to use `keyCode` as the main way to set the key, but it seems to be [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and the new alternatives are [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) and [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key), specially the last one.
>
> Perhaps we might want to start using it, or maybe assume that integers mean `keyCode` and strings mean `key`.

### PR DESCRIPTION
**Pull request by cibernox**
Closes #265

Now: `triggerKeyEvent(selector, 'keydown', 9)` and `triggerKeyEvent(selector, 'keydown', 'Tab')` are equivalent.
Also, the generated event in both cases has `e.keyCode === 9` and `e.key === 'Tab'`

### CODE REVIEW

**Comment by cibernox** [comment]
Test failures seems unrelated to this change 🤔

File: tests/unit/dom/trigger-key-event-test.js [hunk 1]
```diff
@@ -123,4 +123,110 @@ module('DOM Helper: triggerKeyEvent', function(hooks) {
...
+    await checkKey(40, 'ArrowDown');
+    await checkKey(91, 'Meta');
+    await checkKey(93, 'Meta');
+    await checkKey(187, '=');
+    await checkKey(189, '-');
+    await checkKey(65, 'a');
+    await checkKey(90, 'z');
+    await checkKey(65, 'A', { shiftKey: true });
+    await checkKey(90, 'Z', { shiftKey: true });
+    assert.verifySteps([
```
Comment (cibernox) [inline tests/unit/dom/trigger-key-event-test.js]: Btw, verifing steps like this is pretty annoying. Is there a way to avoid this?

**Comment by localpcguy** [comment]
Just cause it may be helpful, @wesbos made a utility site at keycode.info and in the JS he has a pretty comprehensive mapping keyCodes to their English equivalent. 
https://github.com/wesbos/keycodes/blob/gh-pages/scripts.js#L3

It isn't mapped to key values directly, but a more English representation of what that keycode is, but I thought it might be helpful to ensure this provides a larger set of available keyCodes.

**Comment by cibernox** [comment]
This should be green now

File: addon-test-support/@ember/test-helpers/dom/trigger-key-event.js [hunk 2]
```diff
@@ -48,11 +131,17 @@ export default function triggerKeyEvent(target, eventType, keyCode, modifiers =
       );
     }
 
-    if (!keyCode) {
-      throw new Error(`Must provide a \`keyCode\` to \`triggerKeyEvent\``);
+    if (key === null || key === undefined) {
```
Comment (rwjblue) [inline addon-test-support/@ember/test-helpers/dom/trigger-key-event.js]: Can we instead check that they are as expected?

```js
let keyType = typeof key;
if (keyType !== 'number' && keyType !== 'string') {
  throw new Error(...);
}
```

File: addon-test-support/@ember/test-helpers/dom/trigger-key-event.js [hunk 3]
```diff
@@ -12,21 +12,104 @@ const DEFAULT_MODIFIERS = Object.freeze({
...
+}
+
 /**
   Triggers a keyboard event on the specified target.
 
   @public
   @param {string|Element} target the element or selector to trigger the event on
   @param {'keydown' | 'keyup' | 'keypress'} eventType the type of event to trigger
-  @param {string} keyCode the keyCode of the event being triggered
+  @param {number|string} key the keyCode of the event being triggered
```
Comment (rwjblue) [inline addon-test-support/@ember/test-helpers/dom/trigger-key-event.js]: The docs here still refer to this as `the keyCode of the event being triggered`, but it seems that its now either they key or the keycode.

Can you also add more prose to the description above regarding this argument? Perhaps even an example of each way and a link to MDN or something?

File: tests/unit/dom/trigger-key-event-test.js (hunk 1 above)
Comment (rwjblue) [reply tests/unit/dom/trigger-key-event-test.js]: Don't build an "instrumented element", thats why you have to verify in this manner (because the instrumented elements also assert no other events are fired via steps).

**Comment by cibernox** [comment]
Improved 😄

**Comment by rwjblue** [comment]
Thank you @cibernox !
